# Generated by Django 4.2.7 on 2023-11-08 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planner',
            old_name='subject',
            new_name='course',
        ),
        migrations.AddField(
            model_name='planner',
            name='completion_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planner',
            name='goals',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planner',
            name='hours',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planner',
            name='details',
            field=models.TextField(),
        ),
    ]
